

debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "stage.ho-italia.it"
watch = true
exposedByDefault = false

[acme]
email = "webmaster@ogilvy.it"
storageFile = "/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[traefikLog]
  filePath = "/var/log/traefik.log"

[accessLog]
  filePath = "/var/log/access.log"
